version: '3.9'

services:
  app:
    build:
      context: .
    container_name: grandchef_laravel
    ports:
      - "${APP_PORT:-8000}:80"
      - "${REVERB_PORT:-8080}:8080"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/sites-enabled/default
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/nginx:/var/log/nginx
    environment:
      POSTGRES_DB: aiq_db
      POSTGRES_DB_TEST: aiq_db_test
      POSTGRES_USER: aiq_usuario
      POSTGRES_PASSWORD: aiq_senha
    depends_on:
      - db
      - test_db
      - redis

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: aiq_db
      POSTGRES_USER: aiq_usuario
      POSTGRES_PASSWORD: aiq_senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgres:13
    container_name: postgres_db_test
    environment:
      POSTGRES_DB: aiq_db_test
      POSTGRES_USER: aiq_usuario
      POSTGRES_PASSWORD: aiq_senha
    ports:
      - "5433:5432"
    volumes:
      - pgtestdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  pgtestdata:
  redisdata:
